name: Firebase Deployment

'on':
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  fe-build-and-deploy:
    name: Frontend - Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-vue3-vite
    steps:
        # Initial pipeline setup 
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Initialize Node and Cache Dependencies
        uses: actions/setup-node@master
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend-vue3-vite/package-lock.json
        # Install node dependencies
      - name: Install Dependencies
        run: npm install

        # Build angular app with dev configuration
      - name: Build dev app
        run: npm run build

        # Archive dev artifact
      - name: Archive dev artifact
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: ./frontend-vue3-vite/dist

        # Deploy app to Firebase
      - name: Deploy app to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}
          PROJECT_ID: "recursion-tech-llc-website"
          PROJECT_PATH: "./frontend-vue3-vite"
      - run: echo "If you made it this far, high fives all around!"
 
